fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.11.0
    augeasproviders_core:
      repo: git://github.com/hercules-team/augeasproviders_core.git
    augeasproviders_shellvar:
      repo: git://github.com/hercules-team/augeasproviders_shellvar.git
    network:
      repo: git://github.com/razorsedge/puppet-network.git
      ref: 3.2.0
  symlinks:
    infiniband: "#{source_dir}"
