name    'treydock-infiniband'
version '0.1.0'
source 'git://github.com/treydock/puppet-infiniband.git'
author 'treydock'
license 'Apache License, Version 2.0'
summary 'Infiniband module'
description 'Infiniband module'
project_page 'http://github.com/treydock/puppet-infiniband'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
dependency 'domcleal/augeasproviders', '>= 1.0.2'
dependency 'razorsedge/network', '3.x'
