name    'treydock-infiniband'
version '0.1.0'
source 'UNKNOWN'
author 'treydock'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
dependency 'domcleal/augeasproviders', '>= 1.0.2'
